name: Build

on:
  push:
    tags:
      - 'v*.stable*'
      - 'v*.dev*'

jobs:
  test:
    uses: ./.github/workflows/python-tests.yml
  docker:
    runs-on: ubuntu-22.04
    needs:
      - test
    if: ${{ always() && !cancelled() && needs.test.result == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set Variables
        run: |
          echo TAG=${GITHUB_REF#"refs/tags/v"} >> "$GITHUB_ENV"
          if [[ "$TAG" == *stable* ]]; then echo BUILD_TYPE=stable >> "$GITHUB_ENV"; else echo BUILD_TYPE=latest >> "$GITHUB_ENV"; fi
      - name: Make sure things work...
        run: |
          echo $TAG
          echo $BUILD_TYPE
          echo ${{ github.repository }}
      - name: Build & Push Container
        run: |
          docker build --build-arg version=$TAG --build-arg branch=$BUILD_TYPE -t ${{ github.repository }}:$TAG -t ${{ github.repository }}:$BUILD_TYPE -f ./Dockerfile .
          docker push ${{ github.repository }} --all-tags
